#index:
#    path: /
#    controller: App\Controller\DefaultController::index
#index:
 # path: /
  #template: App\template\home\index.html.twig
  #index:
   # path: /
   # defaults: { _controller: 'App\Controller\AccueilController::index' }

#index:
 #   path: /AccueilController/
  #  defaults: { _controller: 'App\Controller\AccueilController::index' }

